### ISSUE TITLE
Phrase blocking

### ISSUE THREAD

**Issue by MacgyverJohnson** [hpaolini/procon#10]
# **Feature request**
Can phrase blocking using wildcards and regular expression  be implemented? For instance on may cases u are not allowed to give spaces or intentionally do not give spaces . Then if u use offensive words it wont be blocked. Example: Let brown and orange be offensive words. If it appears with space[ brown orange] it will be blocked but if it appears without space[ brownorange ] it wont be blocked. 
I use only the profanity filter in procon latte Firefox v45 .  I use Opendns to block adult sites . Also  do u know any other profanity filter subscriptions ...the one provided by default was last Updated: Tue May 03 2011 . I found one here https://gist.githubusercontent.com/ryanlewis/a37739d710ccdb4b406d/raw/0fbd315eb2900bb736609ea894b9bde8217b991a/google_twunter_lol This was was actually a simplified fork of https://gist.github.com/jamiew/1112488 
but need more
TIA in advanced @hpaolini

**Comment by hpaolini** [comment]
Sorry for the late reply.

ProCon does support regular expressions. You could use `\w*` as a wildcard.

`brown\w*` or `\w*orange` would also block `brownorange`.

Hope that helps.
