### ISSUE TITLE
Passwod protection glitch

### ISSUE THREAD

**Issue by MacgyverJohnson** [hpaolini/procon#11]
While the preference page of procon latte is password protected, it can be disabled without the password...most probably after it was given "NO RESTART" ability . Pls look into it @hpaolini

**Comment by hpaolini** [comment]
The expected result is to be prompted for the password when you access the add-ons page. Just tested on Firefox 45.0.2 and still working as expected.

If this does not occur, could you please give me a step-by-step example to test?

Thanks

**Comment by MacgyverJohnson** [comment]
about:config........password protected
type about:config?sync{or anything} ......bypassed with ease........enjoy responsibly

**Comment by hpaolini** [comment]
Awesome report. Fixed the URL bug, and updated [install.xpi](https://github.com/hpaolini/procon/raw/master/install.xpi). One thing though, I can't quite tell from the GIF if you opened the add-ons window the same way as you did with the config.

**Comment by MacgyverJohnson** [comment]
i am using a side bar which make a lot of windows such as console, addons, bookmarks ,history downloads and lots more...u can check it out omnisidebar https://addons.mozilla.org/en-US/firefox/addon/omnisidebar/?src=userprofile
the author Quicksilver also uses github for his addons and is very punctual His github page https://github.com/Quicksaver/OmniSidebar
I went to about:about (which has a list of all about: pages of firefox) first then to about:config

**Comment by MacgyverJohnson** [comment]
Yep!! the bug is fixed
