### ISSUE TITLE
google and access to phornography photos

### ISSUE THREAD

**Issue by xfr82** [hpaolini/procon#16]
Recently I must add "google" to Whitelist because it was blocked by procon on Firefox.
When "google" is on whitelist, my son can write on "google browser" something vulgar like "boobs" or "wet tshirt" and then he have a lot of phornography photos.
When I don't add "google" to the whitelist I can't use google browser.

I think that, when the blacklist was prior then whitelist then the problem will be solved.

Please help - this is important.
Thanks you in advance.

**Comment by hpaolini** [comment]
Keyword `google` should not be in the whitelist. The filter will not block search pages if they are safe; it will, however, block search pages that contain unsafe material.

**Comment by xfr82** [comment]
Thanks you for your answer. But that does not solve the problem. When I remove "google" from the whitelist, my son can't use goole browser. How can in these times do not use the browser google? It is impossible.
Procon is the best antiporn soft ever, really. But some times ago it was be better, when "google" wasn't blocked. I has added all forbidden words like "wet tshirt" or "boobs", and it not possible to search erotic pictures.
Is it possible to return to a state that was once, when the google browser was not blocked?

Thanks you in advance.

**Comment by hpaolini** [comment]
Google was never added to a blocked list; I'm not sure what you mean.

**Comment by xfr82** [comment]
Sorry, I take mistake.
I mean that you can't use google browser when you have ProCon Latte. You have use google browser only when you add google to the white list. But then you can see erotic picture like "wet tshirt" or "body painting".
Sometime ago you can use google browser without problems and you can't see erotic picture, when you have add all forbidden words (like "wet tshirt") to block list.
It was better sometime ago. Is it any possible to go back to past state?

Thanks you in advance.

**Comment by hpaolini** [comment]
> I mean that you can't use google browser when you have ProCon Latte.

Do you actually mean Google Chrome browser or Google.com (the search engine)?
