### ISSUE TITLE
Whitelist as suscription

### ISSUE THREAD

**Issue by Lucasgl1985** [hpaolini/procon#17]
Hello!
Is it possible to create a whitelist from a subscription?
How should the file format be?
I try the following (looking at the exported file), but it did not work:

whitelist.sites =
URL1
URL2

regards

**Comment by hpaolini** [comment]
Have you enabled the whitelist in your settings?

**Comment by inrejimd** [comment]
I am adding to this persons question.  I have whitelist enabled.  I have a file with all the approved websites, but thinking the beginning of this isn't correct.
Does the TXT file need to begin with:
whitelist.sites =
to actually recognize the file?

**Comment by hpaolini** [comment]
The file must begin with `[ProCon Latte 4.0]` then on a newline you have your settings.

It's easier to export the settings file, modify it, and use that as subscription file.
