### ISSUE TITLE
ProCon Latte Update

### ISSUE THREAD

**Issue by globalogicom** [hpaolini/procon#2]
You just pushed out an update Procon latter 4.0.1 that has a bug. When you type in your password to the pop up, it shows the password and not the * symbols when you type as it should. It is windows 7 and Firefox 44.0.Please fix, thanks

**Comment by Rangnarok123** [comment]
Yep, please change it so the password is shown in asterisk like before.

**Comment by hpaolini** [comment]
Thanks, fixed. Also updated the [install.xpi](https://github.com/hpaolini/procon/blob/master/install.xpi) file.
