### ISSUE TITLE
Also search for blocked keywords on whitelist

### ISSUE THREAD

**Issue by DerKieler** [hpaolini/procon#20]
Hello,
I wanted to ask, if it's possible to create an option, that procon search for blocked words, when the access is limited to withelist.
For example google is on whitelist and the access is limited to whitelist procon does'nt search for blocked word on whitelist.
Now I use a second filter to block this keyword, but an easier way would be an other option.

Thanks and Greetings from germany

**Comment by hpaolini** [comment]
I'm not sure I understand. The filter should already be ignoring blacklisted words if you're on a whitelisted page.

**Comment by DerKieler** [comment]
Wow, thank you for your fast answer,

> The filter should already be ignoring blacklisted words

Yes, that's right.
And I'm asking for an option to change this.

I limit access to whitelist. ("Limit Internet access to the Whitelist of approved sites")
This is very usefull and save, BUT I can not filter this sites with a black list.

So my ideas:
-A second blacklist only for whitelist 
-OR an option to enable blacklist for whitelist sites.

**Comment by hpaolini** [comment]
> -A second blacklist only for whitelist
> -OR an option to enable blacklist for whitelist sites.

I'm still not understanding why you would want to block content from a whitelisted site.

Assuming you are on Google (and `google.com` is in the whitelist) and you come across a link that may contain blacklisted content, then the filter will trigger anyways, without needing another blacklist.

If, though, you are worried about search content from `google.com`, then it shouldn't be in the whitelist in the first place.

**Comment by DerKieler** [comment]
Ah okay.
I understand what you mean.
And you are totally right. I'm not afraid of 'black' links but pictures and videos.

There are a lot of websites that are really usefull and normally harmless like _wikipedia_/_facebook/(and yes) _google but also are linked to some adult stuff.
In this way I can put _google on the whitelist AND block the part of google with videos and pictures.
You can use wikipedia without links to adult movies,...

Only a blacklist is in many cases not enough, there are sites in spanish, chinese, japenese,... So I am limiting acces to a couple of sites ( more than 200) that are usefull.
And some of them are essential but white AND black...
