### ISSUE TITLE
Firefox 50+

### ISSUE THREAD

**Issue by DerKieler** [hpaolini/procon#21]
Hi,
I use this amazing Add-on for about four years. And everything is fine. It#s still the best Add-on to filter also the content of websites.

Since I've updated Firefox to version 50.0.2 this Add-on doesn't seems to work at all. It doesn't block any website. The only function that remains is asking for the password to get access to the configuration of Firefox.
I didn't changed anything but updating Firefox.
It doesn't seem to be just my issue https://addons.mozilla.org/de/firefox/addon/procon-latte/reviews/?src=api

Can you repeat this bug by updating Firefox?

I hope that it's just a matter of a few minutes.
Thankyou and greetings

![procon lauft nicht](https://cloud.githubusercontent.com/assets/25006985/22054401/b006d0f8-dd55-11e6-88c9-b8c55e31a4fe.png)

**Comment by hpaolini** [comment]
This is weird. Can't seem to replicate it. I'm also using Firefox 52.0a2 and it seems to work fine. Could you please export your settings file?
