### ISSUE TITLE
Weird spacing after special characters

### ISSUE THREAD

**Issue by FlintWestwood** [hpaolini/procon#24]
Hi,

I like your app a lot, but I've come up with a weird bug. All websites have weird spacings. Before and after a special character I get a space.
For example:
Original: "ProCon can filter any kind of material (pornography, gambling, hacking, cracking, etc...), it can also block all traffic, making sure that only desired websites (those in the whitelist) can be accessed. It also includes a profanity filter."

 Add-On active: "ProCon can filter any kind of material ( pornography , gambling , hacking , cracking , etc ...), it can also block all traffic , making sure that only desired websites ( those in the whitelist ) can be accessed . It also includes a profanity filter ."

Could you please update the app. I would love to stay pornfree again :(

**Comment by FlintWestwood** [comment]
Sorry, I am using Firefox Mobile on Android 7.

**Comment by hpaolini** [comment]
Try disabling the profanity filter and report back.

**Comment by FlintWestwood** [comment]
Yeah, that did the trick! Thanks a lot!

**Comment by hpaolini** [comment]
If that's the case, you might have a keyword in your profanity list that is causing issues. Check for blank spaces/lines or special characters.
