### ISSUE TITLE
Can't open Preferences. Doesn't block anything

### ISSUE THREAD

**Issue by Rangnarok123** [hpaolini/procon#3]
Hi There,

It seems a new issue has risen after today's update. I can't open the Preferences anymore from FireFox Add-on. I tried this after reinstalling the add-on too but that didn't help.

I tried to type in a few blocked words and ProCon didn't pop up at all. Could you please have a look?

Thank you

**Comment by Trud09** [comment]
I also have an issue with the update. I used the block all sites except white listed ones checked and that feature is not working. I figured it was a related issue.

**Comment by hpaolini** [comment]
Does downgrading to the 3.3.* version work? Could you export your settings for me to test? I haven't had success in replicating the bug.

Also, are there any errors in the error console?

**Comment by hpaolini** [comment]
@Trud09 can you access the preferences? If yes, is the blacklist checkbox checked?

**Comment by Trud09** [comment]
I just tested with both it checked an unchecked. I am about to downgrade and check. I am on Xubuntu 14.04 default browser if that matters (Firefox of course)

**Comment by Trud09** [comment]
I just tried to downgrade and I couldn't find it. Do I need to download it separately?

**Comment by hpaolini** [comment]
@Trud09 I assume you are using the latest firefox stable build. Could you please export your settings?

You can downgrade by installing any version from [here.](https://addons.mozilla.org/en-US/firefox/addon/procon-latte/versions/)

**Comment by hpaolini** [comment]
I'm receiving reports that this problem is mainly affecting Firefox 38. I have tested it and, sure enough, there is an undefined typeError for the parent process message manager.

Could you confirm the Firefox version?

**Comment by Rangnarok123** [comment]
Hi there,

Thank you for replying.
The firefox version I had was 43.0.1.

Without changing anything, I updated to 44.0. and ProCon just pops back to life by itself. Tried a few blocked things and it just worked. I don't think it's to do with the settings, but if you need, I can export it.

**Comment by hpaolini** [comment]
@Rangnarok123 That's fine. I just figured it's not compatible with version 38 and 43. Somehow, in those versions the message manager is acting up. Will do some more testing and I'll go from there. Thanks for testing.

**Comment by Trud09** [comment]
I updated to the newest version of Firefox and it is working again. Thank you for your work.

**Comment by hpaolini** [comment]
Cool. I will close this issue then.
