### ISSUE TITLE
Can we add the installer executable into this github project? 

### ISSUE THREAD

**Issue by onguarde** [hpaolini/procon#33]
Firefox addon page has removed this legacy addon. I can't find it anywhere on the internet. 

I managed to extract the installer xpi from my local firefox. And posted the link in the next comment. But I think it's safer for everyone for it to be on github instead of Google drive.

**Comment by onguarde** [comment]
I'm still using Procon filter, just stay on older version of firefox. 56.0.
It still works on both android and the desktop!

Firefox 56.0.2 download,
https://ftp.mozilla.org/pub/firefox/releases/56.0.2/ (Windows)
https://www.apkmirror.com/apk/mozilla/firefox/firefox-56-0-release/ (Android)

Procon latte filter has been removed from Firefox addon webpage. You can download it from here,
[ link removed ]

Note: above will work on android too. Just open the install.html
This is workaround, details in here,
https://stackoverflow.com/questions/32615103/how-to-install-my-xpi-on-firefox-android

Let me know if you need any help setting this up.

**Comment by hpaolini** [comment]
Hi

- Latest version: [https://github.com/hpaolini/procon/blob/master/install.xpi](https://github.com/hpaolini/procon/blob/master/install.xpi)
- Older versions: [https://github.com/hpaolini/procon/tree/master/old_versions](https://github.com/hpaolini/procon/tree/master/old_versions)

For security, please refrain from linking to xpi files hosted elsewhere.
