### ISSUE TITLE
ProCon Latte 4.0.2 No Restart in Firefox

### ISSUE THREAD

**Issue by sheira** [hpaolini/procon#5]
Since updating Firefox to 40.0.2, ProCon Latte lets the user go to websites not on the whitelist, even though our settings are the same.  We tried reverting to our Old Firefox Data, but ProCon is no longer available as a choice to download from Firefox add-ons.

The following website says "No Restart." Does this mean that the 4.0.2 filter will not be available from now on, or does it mean that we just need to donate $5?

https://addons.mozilla.org/en-US/firefox/addon/procon-latte/

We love the ProCon filter and would love to be able to keep using it.

**Comment by hpaolini** [comment]
What version of Firefox are you using? Please make sure you are using the latest version from [https://getfirefox.com](https://getfirefox.com).

**Comment by sheira** [comment]
Dear Hunter,

Thank-you so much for writing back.  ProCon had stopped working when we
updated to Firefox 40.0.2.  I see that there is a latest version of Firefox
now, 44.02, which did correct the problem.  Thanks for your advice!

Sheira

**Comment by hpaolini** [comment]
:thumbsup:
