### ISSUE TITLE
Forbidden page blocked but thumbshot created on new tab page

### ISSUE THREAD

**Issue by Draky50110** [hpaolini/procon#6]
Hello.

Found an issue.
I have installed ProConLatte.

Trying to go to http://www.sex.com : page is blocked.

But if I click on the new tab button, Firefox displays last websites visited with a snapshot.
And the snapshot for sex.com is here, with image of... sex :p 

Any possibility to not display it ?

**Comment by hpaolini** [comment]
The reason you're seeing the thumbnail, even though ProCon blocks the page, is because that thumbnail was cached sometime when ProCon was disabled.

Make sure you have the filter enabled, then clear your browser history and cache. You shouldn't see anymore thumbnails from blocked pages.

**Comment by Draky50110** [comment]
Ok, thanks for the tip :)
