### ISSUE TITLE
Firefox update seems to have broken the add-on

### ISSUE THREAD

**Issue by jnd3** [hpaolini/procon#9]
Firefox just updated to 45.0.2 on my computer, and now procon is not blocking any sites, even though I have "enable blacklist" (and "block sites" and "block words") checked. If I go to a blacklisted site, it loads like normal. I assume that this is related to the FF update, as procon was working yesterday.

However, other functions (such as password-protecting the add-ons page, etc.) seem to still work as normal.

**Comment by hpaolini** [comment]
What version of ProCon Latte are you using? Latest version of ProCon seems to be working fine with the latest stable version of Firefox (45.0.2).

Please let me know.

**Comment by jnd3** [comment]
Firefox 45.0.2 + Procon Latte 4.0.2

I tried it with all plugins and extensions (except for Procon, obviously) disabled, and it still didn't work, in case that's useful information.

I only assume it is related to the update to 45.0.2, since that was the same day Procon stopped working; I don't actually know that for certain. As far as I know, no other changes have been made to FF settings or configuration recently.

As I said, the blacklist is not working; likewise, checking "limit Internet access to the whitelist of approved sites" under advanced options does not cause any sites to become blocked. But the password protection is still working. I'm not certain whether the profanity filter is working or not, as I'm not certain what it's supposed to do. (If it's supposed to be replacing words on the profanity list with the placeholder symbols, then it isn't working either.)

**Comment by hpaolini** [comment]
Could your export your ProCon settings and attach the output file here? I'll take a look over it.

**Comment by jnd3** [comment]
I've discovered that the issue will be fixed by:
1) hitting "restore default settings"
2) remove Procon from Firefox
3) re-install Procon

For the benefit of anyone with the same problem who finds this page, note that neither removing and re-installing Procon (which I forgot to mention I had also tried earlier), nor restoring the default settings, will, by itself, fix the problem (or, at least, neither did for me). [And remember to save your blacklist/whitelist in a text file or something before you restore the defaults!]

Thank you, and my apologies for any time wasted.

**Comment by hpaolini** [comment]
No apologies needed. I'm still curious on what caused this issue.

If you still have your previous configuration file, I'd be interested in taking a look--I'm guessing some keyword was messing with the filter.
